version: '3.8'

services:
  service-user:
    image: dt-service-user:v1
    container_name: dt-service-user
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - dt-network

  mysql:
    image: mysql:8.0
    container_name: dt-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Dartoo
      MYSQL_USER: manager_dartoo
      MYSQL_PASSWORD: 7765
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql 
    networks:
      - dt-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:

networks:
  dt-network:
    external: true
