version: '3.8'

services:
  user-service:
    image: dt-service-user:v1
    container_name: user-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    # environment:
    #   DB_URL: jdbc:mysql://mysql-dartoo:3306/Dartoo
    #   DB_USERNAME: manager_dartoo
    #   DB_PASSWORD: 7765
    #   JWT_ACCESS_SECRET: asf32d96N64LkL123KNL
    #   JWT_REFRESH_SECRET: ptmltkwret5325tgwteu65ObtoJIHoj1
    #   JWT_REFRESH_PEPPER: u3i2q89prawei2u9x8nDSKJo 
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - dartoo-network
