version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8080"
    env_file:
      - .env-product
    # environment:
    #   DB_URL: jdbc:mysql://mysql-dartoo:3306/Dartoo
    #   DB_USERNAME: manager_dartoo
    #   DB_PASSWORD: 7765
    #   JWT_ACCESS_SECRET: asf32d96N64LkL123KNL
    #   JWT_REFRESH_SECRET: ptmltkwret5325tgwteu65ObtoJIHoj1
    #   JWT_REFRESH_PEPPER: u3i2q89prawei2u9x8nDSKJo 
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - dartoo-network
  mysql:
    image: mysql:8.0.23
    container_name: mysql-dartoo
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Dartoo
      MYSQL_USER: manager_dartoo
      MYSQL_PASSWORD: 7765
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s       # 헬스체크 주기 (5초) [5]
      timeout: 2s        # 헬스체크 시간 초과 (2초)
      retries: 5         # 실패 횟수 허용 (5번) [5]
      start_period: 10s  # 초기 시작 시 대기 시간 (10초)
    restart: always
    networks:
      - dartoo-network

networks:
  dartoo-network:
    driver: bridge
    name: dartoo-network