server:
  port: 8081

spring:
  application:
    name: accountService
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      hibernate.jdbc.time_zone: UTC
  jackson:
    time-zone: UTC

app:
  jwt:
    issuer: "Dartoo"
    access-secret: ${JWT_ACCESS_SECRET}
    refresh-secret: ${JWT_REFRESH_SECRET}
    refresh-pepper: ${JWT_REFRESH_PEPPER}
    access-ttl-seconds: 900
    refresh-ttl-seconds: 1209600


logging:
  level:
    # Spring Security 전체에 대한 디버그 로그 활성화
    org.springframework.security: DEBUG
    # 웹 관련 로그도 함께 보면 좋음
    org.springframework.web: DEBUG