apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: dartoo
  labels:
    app: mysql
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: dartoo
    app.kubernetes.io/component: database
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-dartoo
data:
  01-init.sql: |
    GRANT ALL PRIVILEGES ON dartoo.* TO 'manager_dartoo'@'%';
    FLUSH PRIVILEGES;
    USE dartoo;