apiVersion: v1
kind: ConfigMap
metadata:
  name: dt-user-config
  namespace: dartoo
  labels:
    app: dt-user
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: dartoo
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: dt-user
    app.kubernetes.io/instance: dt-user-dartoo
data:
  SERVER_PORT: "8080"
  # spring 관련 변수
  SPRING_APPLICATION_NAME: dt-service-user
  SPRING_PROFILES_ACTIVE: product
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_SHUTDOWN_TIMEOUT: 30s
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  SPRING_JPA_HIBERNATE_TIME_ZONE: UTC
  SPRING_JACKSON_TIME_ZONE: UTC

  # JPA 및 DB 관련 변수
  DB_URL: jdbc:mysql://mysql-svc:3306/dartoo?useSSL=false&serverTimezone=UTC
  HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect